# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crashing_this_plane.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='crashing_this_plane.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x19\x63rashing_this_plane.proto\"\x11\n\x0fStreamerRequest\"\x12\n\x10StreamerResponse\"\x14\n\x12\x43\x61llProcessRequest\"\x15\n\x13\x43\x61llProcessResponse\"\x1f\n\x0fReturnMeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\" \n\x10ReturnMeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2\xb5\x01\n\x0fWithNoSurvivors\x12\x33\n\x08Streamer\x12\x10.StreamerRequest\x1a\x11.StreamerResponse\"\x00\x30\x01\x12:\n\x0b\x43\x61llProcess\x12\x13.CallProcessRequest\x1a\x14.CallProcessResponse\"\x00\x12\x31\n\x08ReturnMe\x12\x10.ReturnMeRequest\x1a\x11.ReturnMeResponse\"\x00\x62\x06proto3')
)




_STREAMERREQUEST = _descriptor.Descriptor(
  name='StreamerRequest',
  full_name='StreamerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=46,
)


_STREAMERRESPONSE = _descriptor.Descriptor(
  name='StreamerResponse',
  full_name='StreamerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=66,
)


_CALLPROCESSREQUEST = _descriptor.Descriptor(
  name='CallProcessRequest',
  full_name='CallProcessRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=88,
)


_CALLPROCESSRESPONSE = _descriptor.Descriptor(
  name='CallProcessResponse',
  full_name='CallProcessResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=111,
)


_RETURNMEREQUEST = _descriptor.Descriptor(
  name='ReturnMeRequest',
  full_name='ReturnMeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='ReturnMeRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=144,
)


_RETURNMERESPONSE = _descriptor.Descriptor(
  name='ReturnMeResponse',
  full_name='ReturnMeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='ReturnMeResponse.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=178,
)

DESCRIPTOR.message_types_by_name['StreamerRequest'] = _STREAMERREQUEST
DESCRIPTOR.message_types_by_name['StreamerResponse'] = _STREAMERRESPONSE
DESCRIPTOR.message_types_by_name['CallProcessRequest'] = _CALLPROCESSREQUEST
DESCRIPTOR.message_types_by_name['CallProcessResponse'] = _CALLPROCESSRESPONSE
DESCRIPTOR.message_types_by_name['ReturnMeRequest'] = _RETURNMEREQUEST
DESCRIPTOR.message_types_by_name['ReturnMeResponse'] = _RETURNMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StreamerRequest = _reflection.GeneratedProtocolMessageType('StreamerRequest', (_message.Message,), dict(
  DESCRIPTOR = _STREAMERREQUEST,
  __module__ = 'crashing_this_plane_pb2'
  # @@protoc_insertion_point(class_scope:StreamerRequest)
  ))
_sym_db.RegisterMessage(StreamerRequest)

StreamerResponse = _reflection.GeneratedProtocolMessageType('StreamerResponse', (_message.Message,), dict(
  DESCRIPTOR = _STREAMERRESPONSE,
  __module__ = 'crashing_this_plane_pb2'
  # @@protoc_insertion_point(class_scope:StreamerResponse)
  ))
_sym_db.RegisterMessage(StreamerResponse)

CallProcessRequest = _reflection.GeneratedProtocolMessageType('CallProcessRequest', (_message.Message,), dict(
  DESCRIPTOR = _CALLPROCESSREQUEST,
  __module__ = 'crashing_this_plane_pb2'
  # @@protoc_insertion_point(class_scope:CallProcessRequest)
  ))
_sym_db.RegisterMessage(CallProcessRequest)

CallProcessResponse = _reflection.GeneratedProtocolMessageType('CallProcessResponse', (_message.Message,), dict(
  DESCRIPTOR = _CALLPROCESSRESPONSE,
  __module__ = 'crashing_this_plane_pb2'
  # @@protoc_insertion_point(class_scope:CallProcessResponse)
  ))
_sym_db.RegisterMessage(CallProcessResponse)

ReturnMeRequest = _reflection.GeneratedProtocolMessageType('ReturnMeRequest', (_message.Message,), dict(
  DESCRIPTOR = _RETURNMEREQUEST,
  __module__ = 'crashing_this_plane_pb2'
  # @@protoc_insertion_point(class_scope:ReturnMeRequest)
  ))
_sym_db.RegisterMessage(ReturnMeRequest)

ReturnMeResponse = _reflection.GeneratedProtocolMessageType('ReturnMeResponse', (_message.Message,), dict(
  DESCRIPTOR = _RETURNMERESPONSE,
  __module__ = 'crashing_this_plane_pb2'
  # @@protoc_insertion_point(class_scope:ReturnMeResponse)
  ))
_sym_db.RegisterMessage(ReturnMeResponse)



_WITHNOSURVIVORS = _descriptor.ServiceDescriptor(
  name='WithNoSurvivors',
  full_name='WithNoSurvivors',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=181,
  serialized_end=362,
  methods=[
  _descriptor.MethodDescriptor(
    name='Streamer',
    full_name='WithNoSurvivors.Streamer',
    index=0,
    containing_service=None,
    input_type=_STREAMERREQUEST,
    output_type=_STREAMERRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CallProcess',
    full_name='WithNoSurvivors.CallProcess',
    index=1,
    containing_service=None,
    input_type=_CALLPROCESSREQUEST,
    output_type=_CALLPROCESSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReturnMe',
    full_name='WithNoSurvivors.ReturnMe',
    index=2,
    containing_service=None,
    input_type=_RETURNMEREQUEST,
    output_type=_RETURNMERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WITHNOSURVIVORS)

DESCRIPTOR.services_by_name['WithNoSurvivors'] = _WITHNOSURVIVORS

# @@protoc_insertion_point(module_scope)
