# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import crashing_this_plane_pb2 as crashing__this__plane__pb2


class WithNoSurvivorsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Streamer = channel.unary_stream(
        '/WithNoSurvivors/Streamer',
        request_serializer=crashing__this__plane__pb2.StreamerRequest.SerializeToString,
        response_deserializer=crashing__this__plane__pb2.StreamerResponse.FromString,
        )
    self.CallProcess = channel.unary_unary(
        '/WithNoSurvivors/CallProcess',
        request_serializer=crashing__this__plane__pb2.CallProcessRequest.SerializeToString,
        response_deserializer=crashing__this__plane__pb2.CallProcessResponse.FromString,
        )
    self.ReturnMe = channel.unary_unary(
        '/WithNoSurvivors/ReturnMe',
        request_serializer=crashing__this__plane__pb2.ReturnMeRequest.SerializeToString,
        response_deserializer=crashing__this__plane__pb2.ReturnMeResponse.FromString,
        )


class WithNoSurvivorsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Streamer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallProcess(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReturnMe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WithNoSurvivorsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Streamer': grpc.unary_stream_rpc_method_handler(
          servicer.Streamer,
          request_deserializer=crashing__this__plane__pb2.StreamerRequest.FromString,
          response_serializer=crashing__this__plane__pb2.StreamerResponse.SerializeToString,
      ),
      'CallProcess': grpc.unary_unary_rpc_method_handler(
          servicer.CallProcess,
          request_deserializer=crashing__this__plane__pb2.CallProcessRequest.FromString,
          response_serializer=crashing__this__plane__pb2.CallProcessResponse.SerializeToString,
      ),
      'ReturnMe': grpc.unary_unary_rpc_method_handler(
          servicer.ReturnMe,
          request_deserializer=crashing__this__plane__pb2.ReturnMeRequest.FromString,
          response_serializer=crashing__this__plane__pb2.ReturnMeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'WithNoSurvivors', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
